id: fa00955072a04d09817391973eb63fe7
title: Toh_730-Dh%C4%81ra%E1%B9%87%C4%AB_T%C4%81r%C4%81%E2%80%99s_Own_Promise-v2.bo.en
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-094-007
  eft-text-version: 1.1.8 2021
